baseURL = "https://louremedi.github.io/"
languageCode = "en-us"
theme = "almeida-cv"
title = "Lou Remedi"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#000"
colorPrimary = "#666"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#333333"
colorSecondary = "#aaa"
pages = 1
