baseURL = "https://louremedi.github.io/"
languageCode = "en-us"
theme = "almeida-cv"
title = "Lou Remedi"

[params]
colorText = "#010101"
colorBadgeText = "#F8F8F8"
colorBadgeBackground = "#666"
colorColumnText = "#F8F8F8"
colorColumnBackground = "#333333"
colorPageBackground = "#000"
nbPages = 1
